# Generated by Django 4.2 on 2025-06-24 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('Lagrange', 'Interpolación de Lagrange'), ('Trazadores Cúbicos', 'Trazadores Cúbicos Naturales')], max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pasos', models.JSONField()),
                ('grafica_url', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
